/* eslint-disable no-unused-vars */
// src/AvaluoContext.js
import { createContext, useState } from "react";

export const AvaluoContext = createContext();

// eslint-disable-next-line react/prop-types
export const AvaluoProvider = ({ children }) => {
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  const [avaluoData, setAvaluoData] = useState({
    folio: "",
    fecha: "",
    colonia: "",
    direccion: "",
    imagen: "",
    titulo: "",
    calle: "",
    numero: "",
    delegacion: "",
    cp: "",
    estado: "",
    dateEvaluo: "",
    valor: "",
    propositoEv: "",
    usoAvaluo: "",
    ncp: "",
    nca: "",
    cla: "",
    tcdc: "",
    usz: "",
    dp: "",
    ca: "",
    usp: "",
    ltp: "",
    ap: "",
    cfe: "",
    via: "",
    alp: "",
    drenaje: "",
    sn: "",
    tu: "",
    vigilancia: "",
    rba: "",
    tlf: "",
    terreno: "",
    colindancia: "",
    disnorte: "",
    colinorte: "",
    dissur: "",
    colisur: "",
    diseste: "",
    colieste: "",
    disoeste: "",
    colioeste: "",
    vreferencia: "",
    adt: "",
    adc: "",
    indiviso: "",
    uadb: "",
    tyc: "",
    ndf: "",
    dh: "",
    ser: "",
    caracp: "",
    //definiciones
    acetados: "",
    mercado: "",
    costos: "",
    ingresos: "",
    negociacion: "",
    ubicacion: "",
    superficie: "",
    calidad: "",
    conservacion: "",
    otros: "",
    baos: "",
    estacionamiento: "",
    construccion: "",
    niveles: "",
    edad: "",
    remanente: "",
    vida: "",
    proyecto: "",
    rentarse: "",
    estado_de_conservacion: "",
    caproyecto: "",
    urs: "",
    cimientos: "",
    estructura: "",
    muros: "",
    entrepisos: "",
    azoteas: "",
    bardas: "",
    banosM: "",
    p1: "",
    p2: "",
    p3: "",
    p4: "",
    p5: "",
    p6: "",
    p7: "",
    p8: "",
    p9: "",
    m1: "",
    m2: "",
    m3: "",
    m4: "",
    m5: "",
    m6: "",
    m7: "",
    m8: "",
    m9: "",
    pl1: "",
    pl2: "",
    pl3: "",
    pl4: "",
    pl5: "",
    pl6: "",
    pl7: "",
    pl8: "",
    pl9: "",
    carpinteria: "",
    muebles: "",
    instalaciones: "",
    puerta: "",
    herreria: "",
    vidreria: "",
    cerrajeria: "",
    fachada: "",
    especiales: "",
    tel1: "",
    tel2: "",
    tel3: "",
    tel4: "",
    tel5: "",
    colonia1: "",
    colonia2: "",
    colonia3: "",
    colonia4: "",
    num1: "",
    num2: "",
    num3: "",
    num4: "",
    url1: "",
    url2: "",
    url3: "",
    url4: "",
    des1: "",
    des2: "",
    des3: "",
    des4: "",
    oferta1: "",
    oferta2: "",
    oferta3: "",
    oferta4: "",
    sup1: "",
    sup2: "",
    sup3: "",
    sup4: "",
    me1: "",
    me2: "",
    me3: "",
    me4: "",
    neg1: "",
    neg2: "",
    neg3: "",
    neg4: "",
    ubi1: "",
    ubi2: "",
    ubi3: "",
    ubi4: "",
    super1: "",
    super2: "",
    super3: "",
    super4: "",
    ca1: "",
    ca2: "",
    ca3: "",
    ca4: "",
    edo1: "",
    edo2: "",
    edo3: "",
    edo4: "",
    otro1: "",
    otro2: "",
    otro3: "",
    otro4: "",
    fre1: "",
    fre2: "",
    fre3: "",
    fre4: "",
    cuadrado1: "",
    cuadrado2: "",
    cuadrado3: "",
    cuadrado4: "",
    homologado: "",
    en: "",
    contruccion: "",
    subtotal: "",
    valorC: "",
    d1: "",
    d2: "",
    d3: "",
    d4: "",
    d5: "",
    d6: "",
    d7: "",
    d8: "",
    d9: "",
    d10: "",
    d11: "",
    d12: "",
    municipio: "",
    costo1: "",
    costo2: "",
    costo3: "",
    costo4: "",
    monto1: "",
    monto2: "",
    monto3: "",
    monto4: "",
    colonia11: "",
    colonia12: "",
    colonia13: "",
    colonia14: "",
    supTerreno1: "",
    supTerreno2: "",
    supTerreno3: "",
    supTerreno4: "",
    loca1: "",
    loca2: "",
    loca3: "",
    loca4: "",
    num21: "",
    num22: "",
    num23: "",
    num24: "",

    costo11: "",
    costo12: "",
    costo13: "",
    costo14: "",

    monto11: "",
    monto12: "",
    monto13: "",
    monto14: "",
    supTerreno11: "",
    supTerreno12: "",
    supTerreno13: "",
    supTerreno14: "",

    sup11: "",
    sup12: "",
    sup13: "",
    sup14: "",

    nombre11: "",
    nombre12: "",
    nombre13: "",
    nombre14: "",

    niveles11: "",
    niveles12: "",
    niveles13: "",
    niveles14: "",
    r1: "",
    r2: "",
    r3: "",
    r4: "",
    ba11: "",
    ba12: "",
    ba13: "",
    ba14: "",
    esta11: "",
    esta12: "",
    esta13: "",
    esta14: "",
    // Agrega otros campos según necesites
  });

  const updateAvaluoData = (key, value) => {
    setAvaluoData((prevData) => ({
      ...prevData,
      [key]: value,
    }));
  };

  return (
    <AvaluoContext.Provider
      value={{ avaluoData, updateAvaluoData, setAvaluoData }}
    >
      {children}
    </AvaluoContext.Provider>
  );
};
